<?php
/**
 * Created by PhpStorm.
 * User: AntoineEisele
 * Date: 16/11/2015
 * Time: 19:01
 */
namespace AppBundle\Entity;
/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
}